name: ESEP
channels:
  - conda-forge
dependencies:
  - cartopy>=0.20
  - matplotlib>=3.5.0
  - more-itertools
  - netCDF4>=1.5.8
  - numpy>=1.20.3
  - openpyxl>=3.0
  - pandas>=1.3.4
  - pint>=0.9
  - pygeos>=0.12
  - pyproj>=3.3.0
  - python>=3.8
  - python-dateutil>=2.8
  - python-docx>=0.8.6
  - pytz>=2021.1
  - pyyaml
  - scipy>=1.7.1
  - utide>=0.2
  - xlrd>=2.0